In [27]:
# HW 2 Anjana Komali Lakshmi Tejaswini, James Foster
# Group 11

In [28]:
# predict attendance based on 1) month, 2) d_o_w , 3) temp, 4) skies and 5) bobblehead 

In [49]:
# import libraries
from sklearn import linear_model
from sklearn import preprocessing
from sklearn.linear_model import Ridge
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error
import numpy as np
import pandas as pd

In [46]:
# read traning data
pd_train = pd.read_csv("dodgers_training.csv")

# print the dataframe
pd_train[:7]

Unnamed: 0 month  day  attend day_of_week opponent  temp   skies day_night  \
0          58   AUG   20   36878      Monday   Giants    80  Clear      Night   
1          62   AUG   25   40284    Saturday  Marlins    70  Clear      Night   
2          56   AUG    7   55024     Tuesday  Rockies    80  Clear      Night   
3           6   APR   23   26376      Monday   Braves    60  Cloudy     Night   
4          57   AUG    8   37084   Wednesday  Rockies    84  Clear      Night   
5          27   MAY   29   51137     Tuesday  Brewers    74  Clear      Night   
6          18   MAY   14   24312      Monday   Snakes    67  Clear      Night   

  cap shirt fireworks bobblehead  
0  NO    NO        NO         NO  
1  NO    NO        NO         NO  
2  NO    NO        NO        YES  
3  NO    NO        NO         NO  
4  NO    NO        NO         NO  
5  NO    NO        NO        YES  
6  NO    NO        NO         NO

In [45]:
pd_train_trans = pd_train[['attend', 'month','day_of_week', 'temp',  'skies', 'bobblehead']]
pd_train_trans [:7]

attend month day_of_week  temp   skies bobblehead
0   36878   AUG      Monday    80  Clear          NO
1   40284   AUG    Saturday    70  Clear          NO
2   55024   AUG     Tuesday    80  Clear         YES
3   26376   APR      Monday    60  Cloudy         NO
4   37084   AUG   Wednesday    84  Clear          NO
5   51137   MAY     Tuesday    74  Clear         YES
6   24312   MAY      Monday    67  Clear          NO

In [47]:
pd_train_trans.shape

(56, 6)

In [32]:
cat_columns = ['month', 'day_of_week', 'skies', 'bobblehead']
df_processed = pd.get_dummies(pd_train_trans, prefix_sep="__",columns=cat_columns)

In [33]:
df_processed[:7]

attend  temp  month__APR  month__AUG  month__JUL  month__JUN  month__MAY  \
0   36878    80           0           1           0           0           0   
1   40284    70           0           1           0           0           0   
2   55024    80           0           1           0           0           0   
3   26376    60           1           0           0           0           0   
4   37084    84           0           1           0           0           0   
5   51137    74           0           0           0           0           1   
6   24312    67           0           0           0           0           1   

   month__OCT  month__SEP  day_of_week__Friday  day_of_week__Monday  \
0           0           0                    0                    1   
1           0           0                    0                    0   
2           0           0                    0                    0   
3           0           0                    0                    1   
4           0           0                    0                    0   
5           0           0                    0                    0   
6           0           0                    0                    1   

   day_of_week__Saturday  day_of_week__Sunday  day_of_week__Thursday  \
0                      0                    0                      0   
1                      1                    0                      0   
2                      0                    0                      0   
3                      0                    0                      0   
4                      0                    0                      0   
5                      0                    0                      0   
6                      0                    0                      0   

   day_of_week__Tuesday  day_of_week__Wednesday  skies__Clear   skies__Cloudy  \
0                     0                       0              1              0   
1                     0                       0              1              0   
2                     1                       0              1              0   
3                     0                       0              0              1   
4                     0                       1              1              0   
5                     1                       0              1              0   
6                     0                       0              1              0   

   bobblehead__NO  bobblehead__YES  
0               1                0  
1               1                0  
2               0                1  
3               1                0  
4               1                0  
5               0                1  
6               1                0

In [34]:
df_processed.shape

(56, 20)

In [63]:
print("MEAN")
print(df_processed.mean())

print("STANDARD DEVIATION")
print(df_processed.std())

MEAN
attend                    39664.803571
temp                         73.642857
month__APR                    0.160714
month__AUG                    0.214286
month__JUL                    0.089286
month__JUN                    0.089286
month__MAY                    0.232143
month__OCT                    0.017857
month__SEP                    0.196429
day_of_week__Friday           0.178571
day_of_week__Monday           0.142857
day_of_week__Saturday         0.160714
day_of_week__Sunday           0.196429
day_of_week__Thursday         0.089286
day_of_week__Tuesday          0.089286
day_of_week__Wednesday        0.142857
skies__Clear                  0.803571
skies__Cloudy                 0.196429
bobblehead__NO                0.910714
bobblehead__YES               0.089286
dtype: float64
STANDARD DEVIATION
attend                    7939.865887
temp                         8.949207
month__APR                   0.370591
month__AUG                   0.414039
month__JUL                   

In [50]:
X_scaled = preprocessing.scale(df_processed)

In [51]:
X_scaled

array([[-0.35416518,  0.71678692, -0.43759497, ..., -0.49441323,
         0.31311215, -0.31311215],
       [ 0.07869152, -0.41074307, -0.43759497, ..., -0.49441323,
         0.31311215, -0.31311215],
       [ 1.95194689,  0.71678692, -0.43759497, ..., -0.49441323,
        -3.19374388,  3.19374388],
       ...,
       [ 0.35383385,  2.40808189, -0.43759497, ..., -0.49441323,
         0.31311215, -0.31311215],
       [ 2.07598334, -0.74900206,  2.2852182 , ..., -0.49441323,
         0.31311215, -0.31311215],
       [-0.7208098 , -0.29799007, -0.43759497, ..., -0.49441323,
         0.31311215, -0.31311215]])

In [59]:
X_scaled.mean(axis=0)

array([-1.42742960e-16,  4.75809868e-16, -6.34413157e-17,  6.34413157e-17,
        1.58603289e-17, -6.34413157e-17, -1.58603289e-17,  1.58603289e-17,
        6.34413157e-17, -3.17206578e-17, -2.37904934e-17, -7.93016446e-17,
        3.96508223e-17, -7.93016446e-18,  7.93016446e-18,  6.34413157e-17,
       -6.34413157e-17,  3.96508223e-17,  8.32667268e-17,  1.58603289e-17])

In [56]:
X_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])